seed: 1911
dataset: ogbnarxiv # ogbnarxiv/pubmed.
edge_type_selection: # (un-)comment accordingly to specify used subgraphs.
  ogbnarxiv:
    - references
    - author
    - venue
    # - fos
  pubmed:
    - references
    - author
    # - journal
    # - mesh
node_embs: simtg # default/simtg/tape.
data:
  graph_dataset:
    ogbnarxiv: data/ogbnarxiv_heterodata.pt
    pubmed: data/pubmed_heterodata.pt
  simtg_embs:
    ogbnarxiv: data/embeddings/ogbnarxiv_simtg_x_embs.pt
    pubmed: data/embeddings/pubmed_simtg_x_embs.pt
  tape_embs: 
    ogbnarxiv: data/embeddings/ogbnarxiv-tape-seed0.emb
    pubmed: data/embeddings/pubmed-tape-seed0.emb
optimizer:
  lr: 0.001
  weight_decay: 0
model:
  name: SAGE
  hidden_channels: 128
  num_layers: 2
  dropout: 0
early_stop_threshold: 20
epochs: 500
runs: 3
