seed: 1911
dataset: ogbnarxiv # ogbnarxiv/pubmed.
edge_type_selection: # (un-)comment accordingly to specify used subgraphs.
  ogbnarxiv:
    - references
    - author
    - fos
    # - venue
  pubmed:
    - references
    - author
    # - mesh
    # - journal
use_scibert: True # set to False if testing the default SkipGram/BoW features.
data:
  graph_dataset:
    ogbnarxiv: data/ogbnarxiv_heterodata.pt
    pubmed: data/pubmed_heterodata.pt
  embeddings: 
    ogbnarxiv: data/embeddings/ogbnarxiv_scibert_tensor_ordered.pt
    pubmed: data/embeddings/pubmed_scibert_tensor_ordered.pt
optimizer:
  lr: 0.01
  weight_decay: 0.001
scheduler:
  factor: 0.1 
  patience: 10 
  threshold: 0.0001
  min_lr: 0.0001
  cooldown: 20
model:
  name: GCN
  hidden_channels: 256
  num_layers: 2
  dropout: 0.2
early_stop_threshold: 50
epochs: 500
runs: 10
